package actions

import (
	"github.com/cpjudge/cpjudge_webserver/models"
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Question)
// DB Table: Plural (questions)
// Resource: Plural (Questions)
// Path: Plural (/questions)
// View Template Folder: Plural (/templates/questions/)

// QuestionsResource is the resource for the Question model
type QuestionsResource struct {
	buffalo.Resource
}

// List gets all Questions. This function is mapped to the path
// GET /questions
func (v QuestionsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	questions := &models.Questions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Questions from the DB
	if err := q.All(questions); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, questions))
}

// Show gets the data for one Question. This function is mapped to
// the path GET /questions/{question_id}
func (v QuestionsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Question
	question := &models.Question{}

	// To find the Question the parameter question_id is used.
	if err := tx.Find(question, c.Param("question_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, question))
}

// New renders the form for creating a new Question.
// This function is mapped to the path GET /questions/new
func (v QuestionsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Question{}))
}

// Create adds a Question to the DB. This function is mapped to the
// path POST /questions
func (v QuestionsResource) Create(c buffalo.Context) error {
	// Allocate an empty Question
	question := &models.Question{}

	// Bind question to the html form elements
	if err := c.Bind(question); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(question)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, question))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Question was created successfully")

	// and redirect to the questions index page
	return c.Render(201, r.Auto(c, question))
}

// Edit renders a edit form for a Question. This function is
// mapped to the path GET /questions/{question_id}/edit
func (v QuestionsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Question
	question := &models.Question{}

	if err := tx.Find(question, c.Param("question_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, question))
}

// Update changes a Question in the DB. This function is mapped to
// the path PUT /questions/{question_id}
func (v QuestionsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Question
	question := &models.Question{}

	if err := tx.Find(question, c.Param("question_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Question to the html form elements
	if err := c.Bind(question); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(question)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, question))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Question was updated successfully")

	// and redirect to the questions index page
	return c.Render(200, r.Auto(c, question))
}

// Destroy deletes a Question from the DB. This function is mapped
// to the path DELETE /questions/{question_id}
func (v QuestionsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Question
	question := &models.Question{}

	// To find the Question the parameter question_id is used.
	if err := tx.Find(question, c.Param("question_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(question); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Question was destroyed successfully")

	// Redirect to the questions index page
	return c.Render(200, r.Auto(c, question))
}
